name: usermng

networks:
  usermng:
    external: true

services:
  usermng-postgres:
    image: postgres:latest
    container_name: usermng-postgres
    #hostname: localhost
    restart: unless-stopped
    environment:
      - POSTGRES_USER=usermng
      - POSTGRES_PASSWORD=usermng123
      - PGDATA=/data/postgres
    volumes:
      - usermng-postgres:/data/postgres
      - usermng-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  usermng-postgres:
    driver: local
    name: data-usermng-postgres